### PR TITLE
Parse subprogram header and parameter keyword

### LINKED ISSUE #154: Generic list in subprogram not supported.
Borrowing an example from [Ashenden's VHDL-2008: Just the New Stuff](https://books.google.be/books?id=ETxLguPMEY0C&pg):

``` vhdl
procedure swap
  generic ( type T )
  parameter (a, b : inout T) is
  variable temp : T;
begin
  temp := a; a := b; b := temp;
end procedure swap;
```

I get two errors on line two at "type":
"Expected 'is' or ';'" and
"Expected 'library', 'use', 'context', 'entity', 'architecture', 'configuration' or 'package'"

### LINKED ISSUE #191: [BUG] Errors reported when using generic types and generic packages
**Describe the bug**
The following error(s) are reported for the snippet below:
``Expected 'library', 'use', 'context', 'entity', 'architecture', 'configuration' or 'package'vhdl ls``
It seems to be the LS can't handle generic statements.
The error seems to also break the entire linter functionality. Also, even hovering over objects or pressing ctrl button and trying to click on the object to jump to the definition don't work.

**Code**
```vhdl
procedure test_get_stream_data_t_template   
    generic (
        type data_t;
        procedure check_equal(
            constant got            : in data_t;
            constant expected       : in data_t;
            constant msg            : in string := "";
            constant level          : in log_level_t := null_log_level;
            constant path_offset    : in natural := 0;
            constant line_num       : in natural := 0;
            constant file_name      : in string := "")
    )
    parameter (
        mode         : return_types_stream_data_t;
        test_string  : string;
        expected     : data_t;
        converted    : data_t
    ) is
        variable return_type_string: constr_str;
    begin
        if mode = slv_return_type then
            null; -- TODO
        elsif mode = stream_data_return_type then
            null; -- TODO
        else
            error("Invalid mode!");
        end if;
        check_equal(converted, expected, return_type_string);
end procedure;
```

Code to reproduce the error.

**Please complete the following information:**
The code works with Questa Sim 2022.4:

**Screenshots**
image

**Additional context**
This problem was already reported in another LS: https://github.com/TerosTechnology/vscode-terosHDL/issues/408

### PR DESCRIPTION
**Pull request by Schottkyc137**
Closes #191, closes #154 

Now parses and analyzes the examples correctly.

### CODE REVIEW

File: vhdl_lang/src/analysis/tests/visibility.rs [hunk 1]
```diff
@@ -757,3 +757,27 @@ end architecture;
...
+      a := b;
+      b := temp;
+    end procedure swap;
+    variable temp2: T;
+    ",
+    );
+    let (_, diagnostics) = builder.get_analyzed_root();
+    assert_eq!(
+        diagnostics,
+        vec![Diagnostic::error(code.s("T", 4), "No declaration of 'T'")]
```
Comment (kraigher) [inline vhdl_lang/src/analysis/tests/visibility.rs:781]: Note instead of counting to T four times you can do `code.s1("temp2 : T").s1("T")`

**Review by kraigher — APPROVED** [review]

**Comment by kraigher** [comment]
Good work. Might be a bit premature to close the above two issuse ar it is still missing support for instantiation of the generic subprograms and calling them.
