### PR TITLE
Publish better diagnostic for attributes

### LINKED ISSUE #242: Incorrect diagnostic for attributes
The following code snippet:
```vhdl
entity test is
    attribute some_attr : string;
    attribute some_attr of test : signal is "some value";
end entity test;
```
produces the incorrect diagnostic "Attribute specification must be in the immediate declarative part". Instead, it should be something like "some_attr must be of class entity"

### PR DESCRIPTION
**Pull request by Schottkyc137**
Closes #242 

@kraigher is this the desired behavior? See the test below that I had to alter. Was setting `myattr` to `signal` instead of `entity` intentional?

### CODE REVIEW

File: vhdl_lang/src/analysis/declarative.rs [hunk 1]
```diff
@@ -695,6 +695,14 @@ impl<'a> AnalyzeContext<'a> {
...
+            if Some(*entity_class) != get_entity_class(ent) {
+                diagnostics.push(Diagnostic::error(
+                    designator,
+                    format!("{} is not of class {}", ent.describe(), entity_class),
+                ));
+                return Ok(());
+            }
+
             // Attributes affect the underlying entity and cannot be set directly on aliases
             let ent = ent.as_actual();
```
Comment (kraigher) [inline vhdl_lang/src/analysis/declarative.rs:707]: Blocking: Moving the entity class check above this line makes it no longer see through aliases.
